///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class ConnectingBase : State
    {
        public ConnectingBase(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public virtual void ConnectFailedTrigger(string message, int errorCode)
        {
            ((ConnectionStateMachine)stateMachine).Message = message;
            ((ConnectionStateMachine)stateMachine).ErrorCode = errorCode;

            SetState(typeof(Disconnected));
        }

        public virtual void ConnectedTrigger()
        {

            SetState(typeof(Connected));
        }


        // State Behaviors

        public override void body()
        {
            ((ConnectionStateMachine)stateMachine).Do_Connecting();
        }
    }
}
