///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////

using System.Collections.Generic;
using Inspector.Model.BluetoothDongle;
using StateMachines.Base;

namespace Inspector.Connection
{
    public class DisconnectedBase : State
    {
        public DisconnectedBase(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public virtual void DisconnectTrigger()
        {

            SetState(typeof(Disconnected));
        }

        public virtual void ConnectTrigger(Dictionary<string, string> connectionParameters, List<BluetoothDongleInformation> allowedBluetoothDongles)
        {
            ((ConnectionStateMachine)stateMachine).ConnectionParameters = connectionParameters;
            ((ConnectionStateMachine)stateMachine).AllowedBluetoothDongles = allowedBluetoothDongles;

            SetState(typeof(Connecting));
        }


        // State Behaviors

        public override void body()
        {
            ((ConnectionStateMachine)stateMachine).Do_Disconnected();
        }
    }
}
