'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class COMMUNICATORMainResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.COMMUNICATOR.Main.COMMUNICATORMainResx", GetType(COMMUNICATORMainResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup Business logic component:.
        '''</summary>
        Friend Shared ReadOnly Property str_BusinessLogic_component() As String
            Get
                Return ResourceManager.GetString("str_BusinessLogic_component", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Deutsch.
        '''</summary>
        Friend Shared ReadOnly Property str_Deutsch() As String
            Get
                Return ResourceManager.GetString("str_Deutsch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !English.
        '''</summary>
        Friend Shared ReadOnly Property str_English() As String
            Get
                Return ResourceManager.GetString("str_English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The file.
        '''</summary>
        Friend Shared ReadOnly Property str_FileNotExists1() As String
            Get
                Return ResourceManager.GetString("str_FileNotExists1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !does not exists.
        '''</summary>
        Friend Shared ReadOnly Property str_fileNotExists2() As String
            Get
                Return ResourceManager.GetString("str_fileNotExists2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSPECTOR PC.
        '''</summary>
        Friend Shared ReadOnly Property str_INSPECTOR_PC() As String
            Get
                Return ResourceManager.GetString("str_INSPECTOR_PC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Italian.
        '''</summary>
        Friend Shared ReadOnly Property str_Italian() As String
            Get
                Return ResourceManager.GetString("str_Italian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup infra component:.
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_Infra() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_Infra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup synchronize bussiness component:.
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_Synchronize_bussiness() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_Synchronize_bussiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup synchronize database component: .
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_Synchronize_database() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_Synchronize_database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Nederlands.
        '''</summary>
        Friend Shared ReadOnly Property str_Nederlands() As String
            Get
                Return ResourceManager.GetString("str_Nederlands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Polish.
        '''</summary>
        Friend Shared ReadOnly Property str_Polish() As String
            Get
                Return ResourceManager.GetString("str_Polish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Changes are applied after restarting the program. Do you wish to restart the program?.
        '''</summary>
        Friend Shared ReadOnly Property str_Restart_application() As String
            Get
                Return ResourceManager.GetString("str_Restart_application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Russisch.
        '''</summary>
        Friend Shared ReadOnly Property str_Russia() As String
            Get
                Return ResourceManager.GetString("str_Russia", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
