'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")> _
    Partial Friend NotInheritable Class License

        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As License = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New License()), License)

        Public Shared ReadOnly Property [Default]() As License
            Get
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property CompanyName() As string
            Get
                Return CType(Me("CompanyName"), String)
            End Get
            Set
                Me("CompanyName") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property CustomerName() As string
            Get
                Return CType(Me("CustomerName"), String)
            End Get
            Set(value As String)
                Me("CustomerName") = value
            End Set
        End Property
    End Class
End Namespace
