///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class ErrorBase : State
    {
        public ErrorBase(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public virtual void NonFatalErrorTrigger()
        {

            SetState(typeof(Connected));
        }

        public virtual void DisconnectTrigger()
        {

            SetState(typeof(Disconnecting));
        }

        public virtual void ErrorTrigger(string message, int errorCode)
        {
            ((ConnectionStateMachine)stateMachine).Message = message;
            ((ConnectionStateMachine)stateMachine).ErrorCode = errorCode;

            SetState(typeof(Error));
        }

        // State Behaviors

        public override void body()
        {
            ((ConnectionStateMachine)stateMachine).Do_Error();
        }
    }
}
