'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class InitializationErrorCodesResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.INSPECTOR.Infra.InitializationErrorCodesResx", GetType(InitializationErrorCodesResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !An unexpected error occurred in the HAL.
        '''</summary>
        Friend Shared ReadOnly Property Error_1000() As String
            Get
                Return ResourceManager.GetString("Error_1000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The connection properties were not found.
        '''</summary>
        Friend Shared ReadOnly Property Error_1001() As String
            Get
                Return ResourceManager.GetString("Error_1001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !A connection property was not found.
        '''</summary>
        Friend Shared ReadOnly Property Error_1002() As String
            Get
                Return ResourceManager.GetString("Error_1002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !There has been tried to make a connection, but the connection was already active.
        '''</summary>
        Friend Shared ReadOnly Property Error_1003() As String
            Get
                Return ResourceManager.GetString("Error_1003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The specified bluetooth api is not supported by the BT Framework.
        '''</summary>
        Friend Shared ReadOnly Property Error_1004() As String
            Get
                Return ResourceManager.GetString("Error_1004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The bluetooth dongle(s) that are connected to the PC are not found in the allowed dongle list..
        '''</summary>
        Friend Shared ReadOnly Property Error_1005() As String
            Get
                Return ResourceManager.GetString("Error_1005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !No Bluetooth dongles found on the pc..
        '''</summary>
        Friend Shared ReadOnly Property Error_1006() As String
            Get
                Return ResourceManager.GetString("Error_1006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !This error occurs if the last bit is not a stop bit. This generally happens because of synchronization error. You may face this 
        ''' Error when connecting two computers with the help of null 
        '''modem, if the baud rates of the transmitting computer 
        '''differs from the baud rates of the receiving computer..
        '''</summary>
        Friend Shared ReadOnly Property Error_1010() As String
            Get
                Return ResourceManager.GetString("Error_1010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !This error usually occurs when the data are read from the port slower 
        '''than they are received. If you don&apos;t read the incoming bytes fast enough the last byte can be overwritten with the byte which was received last, in this case the last byte may be lost which will cause overrun error..
        '''</summary>
        Friend Shared ReadOnly Property Error_1011() As String
            Get
                Return ResourceManager.GetString("Error_1011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !An input buffer overflow has occurred. There is either no room in the 
        '''input buffer, or a character was received after the end-of-file (EOF) character..
        '''</summary>
        Friend Shared ReadOnly Property Error_1012() As String
            Get
                Return ResourceManager.GetString("Error_1012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !This error occurs if the parity doesn&apos;t coincide with the parameters set when the byte is received..
        '''</summary>
        Friend Shared ReadOnly Property Error_1013() As String
            Get
                Return ResourceManager.GetString("Error_1013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The application tried to transmit a character, but the output buffer was full..
        '''</summary>
        Friend Shared ReadOnly Property Error_1014() As String
            Get
                Return ResourceManager.GetString("Error_1014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !An undefined error occurred on the serial port.
        '''</summary>
        Friend Shared ReadOnly Property Error_1015() As String
            Get
                Return ResourceManager.GetString("Error_1015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not connect to the serial port.
        '''</summary>
        Friend Shared ReadOnly Property Error_1020() As String
            Get
                Return ResourceManager.GetString("Error_1020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not close the serial port.
        '''</summary>
        Friend Shared ReadOnly Property Error_1021() As String
            Get
                Return ResourceManager.GetString("Error_1021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not send the command.
        '''</summary>
        Friend Shared ReadOnly Property Error_1022() As String
            Get
                Return ResourceManager.GetString("Error_1022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The message that was received over the serial port had an incorrect checksum.
        '''</summary>
        Friend Shared ReadOnly Property Error_1030() As String
            Get
                Return ResourceManager.GetString("Error_1030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The message received over the serial port had an incorrect format.
        '''</summary>
        Friend Shared ReadOnly Property Error_1031() As String
            Get
                Return ResourceManager.GetString("Error_1031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !There has been no reaction in a timely manner.
        '''</summary>
        Friend Shared ReadOnly Property Error_1040() As String
            Get
                Return ResourceManager.GetString("Error_1040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !There has been a timeout during measurement.
        '''</summary>
        Friend Shared ReadOnly Property Error_1041() As String
            Get
                Return ResourceManager.GetString("Error_1041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not set the DTR on the serial port..
        '''</summary>
        Friend Shared ReadOnly Property Error_1042() As String
            Get
                Return ResourceManager.GetString("Error_1042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not initialize the serial port..
        '''</summary>
        Friend Shared ReadOnly Property Error_1043() As String
            Get
                Return ResourceManager.GetString("Error_1043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not start the continuous measurement..
        '''</summary>
        Friend Shared ReadOnly Property Error_1044() As String
            Get
                Return ResourceManager.GetString("Error_1044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not stop the continuous measurement..
        '''</summary>
        Friend Shared ReadOnly Property Error_1045() As String
            Get
                Return ResourceManager.GetString("Error_1045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not compute the checksum..
        '''</summary>
        Friend Shared ReadOnly Property Error_1046() As String
            Get
                Return ResourceManager.GetString("Error_1046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !It was tried to send a command while the communication control was not yet claimed.
        '''</summary>
        Friend Shared ReadOnly Property Error_1101() As String
            Get
                Return ResourceManager.GetString("Error_1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !A second attempt was made to claim the communication control without releasing the previous claim first..
        '''</summary>
        Friend Shared ReadOnly Property Error_1102() As String
            Get
                Return ResourceManager.GetString("Error_1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The call to the statemachine was invalid for the current state of the connection statemachine..
        '''</summary>
        Friend Shared ReadOnly Property Error_1103() As String
            Get
                Return ResourceManager.GetString("Error_1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Initialization process finished succesfully.
        '''</summary>
        Friend Shared ReadOnly Property Error_1200() As String
            Get
                Return ResourceManager.GetString("Error_1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The SCPI interface reported at least one, but at most 5 errors.
        ''' The errors encountered are in the first messageParameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1201() As String
            Get
                Return ResourceManager.GetString("Error_1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The SCPI interface reported too many errors (6)
        ''' The errors encountered are in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1202() As String
            Get
                Return ResourceManager.GetString("Error_1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Set Pressure Unit call reported an error. The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1203() As String
            Get
                Return ResourceManager.GetString("Error_1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Check Manometer Range call reported an error. The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1204() As String
            Get
                Return ResourceManager.GetString("Error_1204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Initiate Self Test call reported an error. The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1205() As String
            Get
                Return ResourceManager.GetString("Error_1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Reading the battery limit failed.
        '''</summary>
        Friend Shared ReadOnly Property Error_1206() As String
            Get
                Return ResourceManager.GetString("Error_1206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Battery Level was in an inccorrect format.The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1207() As String
            Get
                Return ResourceManager.GetString("Error_1207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Battery Level is below the Battery level limit
        '''. The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1208() As String
            Get
                Return ResourceManager.GetString("Error_1208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Switching the manometer has failed..
        '''</summary>
        Friend Shared ReadOnly Property Error_1209() As String
            Get
                Return ResourceManager.GetString("Error_1209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Entering Remote Local command mode has failed.
        ''' The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1210() As String
            Get
                Return ResourceManager.GetString("Error_1210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Switching the Initialization led has failed.
        ''' The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1211() As String
            Get
                Return ResourceManager.GetString("Error_1211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Exiting the Remote Local command mode has failed.
        ''' The reply from the device is in the first message parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1212() As String
            Get
                Return ResourceManager.GetString("Error_1212", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Reading the Initialization led address from configuration failed..
        '''</summary>
        Friend Shared ReadOnly Property Error_1213() As String
            Get
                Return ResourceManager.GetString("Error_1213", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Tried to execute an unsupported command..
        '''</summary>
        Friend Shared ReadOnly Property Error_1214() As String
            Get
                Return ResourceManager.GetString("Error_1214", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Step was executed successfully..
        '''</summary>
        Friend Shared ReadOnly Property Error_1215() As String
            Get
                Return ResourceManager.GetString("Error_1215", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The pressure range retrieved from the device is not according to the defined range in the station information for manometer TH1.
        '''</summary>
        Friend Shared ReadOnly Property Error_1216() As String
            Get
                Return ResourceManager.GetString("Error_1216", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The pressure range retrieved from the device is not according to the defined range in the station information for manometer TH2.
        '''</summary>
        Friend Shared ReadOnly Property Error_1217() As String
            Get
                Return ResourceManager.GetString("Error_1217", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The pressure range could not be retrieved from the station information.
        '''</summary>
        Friend Shared ReadOnly Property Error_1218() As String
            Get
                Return ResourceManager.GetString("Error_1218", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Manometer is not present.
        '''</summary>
        Friend Shared ReadOnly Property Error_1219() As String
            Get
                Return ResourceManager.GetString("Error_1219", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Manometer found.
        '''</summary>
        Friend Shared ReadOnly Property Error_1220() As String
            Get
                Return ResourceManager.GetString("Error_1220", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The initialization process encountered a timeout on one or more of the manometers.
        '''</summary>
        Friend Shared ReadOnly Property Error_1297() As String
            Get
                Return ResourceManager.GetString("Error_1297", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The initialization process finished with an error..
        '''</summary>
        Friend Shared ReadOnly Property Error_1298() As String
            Get
                Return ResourceManager.GetString("Error_1298", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The initialization process finished with a warning..
        '''</summary>
        Friend Shared ReadOnly Property Error_1299() As String
            Get
                Return ResourceManager.GetString("Error_1299", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The Inspection process finished succesfully.
        '''</summary>
        Friend Shared ReadOnly Property Error_1300() As String
            Get
                Return ResourceManager.GetString("Error_1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not create the inspection report
        ''' MessageParameter contains the error message..
        '''</summary>
        Friend Shared ReadOnly Property Error_1301() As String
            Get
                Return ResourceManager.GetString("Error_1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not retrieve the station information needed for the result file.
        '''        /// MessageParameter contains the error message.
        '''</summary>
        Friend Shared ReadOnly Property Error_1302() As String
            Get
                Return ResourceManager.GetString("Error_1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not update the inspection report MessageParameter contains the error message..
        '''</summary>
        Friend Shared ReadOnly Property Error_1303() As String
            Get
                Return ResourceManager.GetString("Error_1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The retrieved StepResult had a sequence number that was different from the step that was currently executed..
        '''</summary>
        Friend Shared ReadOnly Property Error_1304() As String
            Get
                Return ResourceManager.GetString("Error_1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The retrieved StepResult was of incorrect result type.
        '''  MessageParameter contains the type that was expected..
        '''</summary>
        Friend Shared ReadOnly Property Error_1305() As String
            Get
                Return ResourceManager.GetString("Error_1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not retrieve the inspection procedure
        ''' MessageParameter contains the error message..
        '''</summary>
        Friend Shared ReadOnly Property Error_1306() As String
            Get
                Return ResourceManager.GetString("Error_1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process was aborted by the user.
        '''</summary>
        Friend Shared ReadOnly Property Error_1307() As String
            Get
                Return ResourceManager.GetString("Error_1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Could not retrieve the inspection procedure name.
        '''</summary>
        Friend Shared ReadOnly Property Error_1308() As String
            Get
                Return ResourceManager.GetString("Error_1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process could not continue because the volumeVak or volumeVa was not unavailable or could not be parsed..
        '''</summary>
        Friend Shared ReadOnly Property Error_1309() As String
            Get
                Return ResourceManager.GetString("Error_1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process encountered an invalid procedure step..
        '''</summary>
        Friend Shared ReadOnly Property Error_1310() As String
            Get
                Return ResourceManager.GetString("Error_1310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process encountered an invalid manometer unit. Supported units are &apos;bar&apos; and &apos;mbar&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Error_1311() As String
            Get
                Return ResourceManager.GetString("Error_1311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process could not update the measurement file..
        '''</summary>
        Friend Shared ReadOnly Property Error_1312() As String
            Get
                Return ResourceManager.GetString("Error_1312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process could not retrieve the required DTR value from the settings file..
        '''</summary>
        Friend Shared ReadOnly Property Error_1313() As String
            Get
                Return ResourceManager.GetString("Error_1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process could not retrieve the connection properties from file..
        '''</summary>
        Friend Shared ReadOnly Property Error_1314() As String
            Get
                Return ResourceManager.GetString("Error_1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process could not prepare the required manometers.
        '''</summary>
        Friend Shared ReadOnly Property Error_1315() As String
            Get
                Return ResourceManager.GetString("Error_1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection process failed to initialize properly..
        '''</summary>
        Friend Shared ReadOnly Property Error_1316() As String
            Get
                Return ResourceManager.GetString("Error_1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !This inspection process could not creat the measurement report..
        '''</summary>
        Friend Shared ReadOnly Property Error_1317() As String
            Get
                Return ResourceManager.GetString("Error_1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The pressure range could not be retrieved from the station information.
        '''</summary>
        Friend Shared ReadOnly Property Error_1320() As String
            Get
                Return ResourceManager.GetString("Error_1320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The continuous measurement could not be stopped..
        '''</summary>
        Friend Shared ReadOnly Property Error_1321() As String
            Get
                Return ResourceManager.GetString("Error_1321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The resolution for the given Pressure Range for manometer TH1 could not be found..
        '''</summary>
        Friend Shared ReadOnly Property Error_1322() As String
            Get
                Return ResourceManager.GetString("Error_1322", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The resolution for the given Pressure Range for manometer TH21 could not be found..
        '''</summary>
        Friend Shared ReadOnly Property Error_1323() As String
            Get
                Return ResourceManager.GetString("Error_1323", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Undefined PLEXOR Bluetooth address.
        '''</summary>
        Friend Shared ReadOnly Property Error_1324() As String
            Get
                Return ResourceManager.GetString("Error_1324", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Specified Bluetooth API is not available.
        '''</summary>
        Friend Shared ReadOnly Property Error_14() As String
            Get
                Return ResourceManager.GetString("Error_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspector could not find the InspectorSettings.xml file.
        '''</summary>
        Friend Shared ReadOnly Property Error_1400() As String
            Get
                Return ResourceManager.GetString("Error_1400", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspector could not load a required setting from the InspectorSettings.xml file..
        '''</summary>
        Friend Shared ReadOnly Property Error_1401() As String
            Get
                Return ResourceManager.GetString("Error_1401", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !RS232 Protocol checksum Error.
        '''</summary>
        Friend Shared ReadOnly Property Error_1600() As String
            Get
                Return ResourceManager.GetString("Error_1600", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Header Error: Too short.
        '''</summary>
        Friend Shared ReadOnly Property Error_1601() As String
            Get
                Return ResourceManager.GetString("Error_1601", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Undefined Header; Undefined command.
        '''</summary>
        Friend Shared ReadOnly Property Error_1602() As String
            Get
                Return ResourceManager.GetString("Error_1602", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Invalid character&quot;: Terminator expected.
        '''</summary>
        Friend Shared ReadOnly Property Error_1603() As String
            Get
                Return ResourceManager.GetString("Error_1603", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Invalid parameter: Out of bounds.
        '''</summary>
        Friend Shared ReadOnly Property Error_1604() As String
            Get
                Return ResourceManager.GetString("Error_1604", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Command protected.
        '''</summary>
        Friend Shared ReadOnly Property Error_1605() As String
            Get
                Return ResourceManager.GetString("Error_1605", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !EEProm Read/Write Erro.
        '''</summary>
        Friend Shared ReadOnly Property Error_1606() As String
            Get
                Return ResourceManager.GetString("Error_1606", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Fatal Command Execution Error.
        '''</summary>
        Friend Shared ReadOnly Property Error_1607() As String
            Get
                Return ResourceManager.GetString("Error_1607", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !MANOMETER_UNKNOWN_ERROR.
        '''</summary>
        Friend Shared ReadOnly Property Error_1608() As String
            Get
                Return ResourceManager.GetString("Error_1608", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Missing parameter.
        '''</summary>
        Friend Shared ReadOnly Property Error_1609() As String
            Get
                Return ResourceManager.GetString("Error_1609", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Specified service was not found (Could not connect).
        '''</summary>
        Friend Shared ReadOnly Property Error_44() As String
            Get
                Return ResourceManager.GetString("Error_44", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
