'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Class KamLicenseResx

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.LicenceTool.KamLicenseResx", GetType(KamLicenseResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !ActivationCode:.
        '''</summary>
        Friend Shared ReadOnly Property str_ActivationCode() As string
            Get
                Return ResourceManager.GetString("str_ActivationCode", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !ComputerKey.
        '''</summary>
        Friend Shared ReadOnly Property str_ComputerKey() As string
            Get
                Return ResourceManager.GetString("str_ComputerKey", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Customer company:.
        '''</summary>
        Friend Shared ReadOnly Property str_Customer_company() As string
            Get
                Return ResourceManager.GetString("str_Customer_company", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Customer name:.
        '''</summary>
        Friend Shared ReadOnly Property str_Customer_name() As string
            Get
                Return ResourceManager.GetString("str_Customer_name", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Demo Key.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyDemo() As string
            Get
                Return ResourceManager.GetString("str_EKeyDemo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !No more licenseactivations allowed.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyExceededAllowInstances() As string
            Get
                Return ResourceManager.GetString("str_EKeyExceededAllowInstances", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !License key expired.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyExpired() As string
            Get
                Return ResourceManager.GetString("str_EKeyExpired", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !License key invalid.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyInvalid() As string
            Get
                Return ResourceManager.GetString("str_EKeyInvalid", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Computer code invalid.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyMachineInvalid() As string
            Get
                Return ResourceManager.GetString("str_EKeyMachineInvalid", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !License needs activation.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyNeedsActivation() As string
            Get
                Return ResourceManager.GetString("str_EKeyNeedsActivation", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !License valid.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyPermanent() As string
            Get
                Return ResourceManager.GetString("str_EKeyPermanent", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Product code invalid.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyProductInvalid() As string
            Get
                Return ResourceManager.GetString("str_EKeyProductInvalid", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !License information is invalid.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyTampered() As string
            Get
                Return ResourceManager.GetString("str_EKeyTampered", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Unexpected license status.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyUnexpected() As string
            Get
                Return ResourceManager.GetString("str_EKeyUnexpected", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Product version invalid.
        '''</summary>
        Friend Shared ReadOnly Property str_EKeyVersionInvalid() As string
            Get
                Return ResourceManager.GetString("str_EKeyVersionInvalid", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !No activation code input.
        '''</summary>
        Friend Shared ReadOnly Property str_NoActivationCode() As string
            Get
                Return ResourceManager.GetString("str_NoActivationCode", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Please sent the mail to registration@wigersma-sikkema.com.
        '''</summary>
        Friend Shared ReadOnly Property str_Please_sent_the_mail_to() As string
            Get
                Return ResourceManager.GetString("str_Please_sent_the_mail_to", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !The application is licensed.
        '''</summary>
        Friend Shared ReadOnly Property str_The_application_is_licensed() As string
            Get
                Return ResourceManager.GetString("str_The_application_is_licensed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !The information is copied to windows clipboard.
        '''</summary>
        Friend Shared ReadOnly Property str_The_information_is_copied_to() As string
            Get
                Return ResourceManager.GetString("str_The_information_is_copied_to", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !Version:.
        '''</summary>
        Friend Shared ReadOnly Property str_Version() As string
            Get
                Return ResourceManager.GetString("str_Version", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to !you can copy the information directly into your mail and sent it to registration@wigersma-sikkema.com.
        '''</summary>
        Friend Shared ReadOnly Property str_you_can_copy_the_information() As string
            Get
                Return ResourceManager.GetString("str_you_can_copy_the_information", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
