
//////////////////////////////////////////////////////////////////////////////////
// Initially Generated by Sioux C# StateMachine Code Generator 					//
//  User changes allowed, requires merging when re-generated		            //
//////////////////////////////////////////////////////////////////////////////////

using System;

namespace Inspector.Connection
{
    public interface IConnectionStateMachineCustom
    {
        // IMPLEMENT YOUR OWN CODE HERE
        /// <summary>
        /// Releases unmanaged and - optionally - managed resources
        /// </summary>
        void Dispose();

        event EventHandler<MessageReceivedEventArgs> MessageReceived;
        event EventHandler<ErrorEventArgs> Error;
        event EventHandler<DisconnectingEventArgs> Disconnecting;
        event EventHandler<DisconnectedEventArgs> Disconnected;
        event EventHandler<ConnectingEventArgs> Connecting;
        event EventHandler<ConnectFailedEventArgs> ConnectFailed;
        event EventHandler<ConnectedEventArgs> Connected;
        event EventHandler<SendCommandEventArgs> SendCommand;
        event EventHandler<RecoveredFromErrorEventArgs> RecoveredFromError;
        event EventHandler<MeasurementEventArgs> MeasurementReceived;
        event EventHandler ContinuousMeasurementStopped;
        event EventHandler ContinuousMeasurementStarted;
        event EventHandler DeviceUnPaired;
        event EventHandler DeviceUnPairFinished;
    }
}  // end namespace Connection 
