
///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////


namespace Inspector.Connection
{
    public interface IConnectionStateMachine : IConnectionStateMachineCustom, IConnectionStateMachineContext
    {
        void Initialize();
    }
}  // end namespace Connection 
