<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007r3sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/PRSData">
		<PRSData>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">T:/SOURCE~1/INSPECTOR.PC/SOURCE~1/KAM.INSPECTOR.Synchronize.Bussiness/PRS/XML/XMLTransformation/StationInformation.xsd</xsl:attribute>
			<xsl:for-each select="PRS">
				<PRS>
					<xsl:for-each select="Route">
						<xsl:variable name="VmarkerloopRoute" select="."/>
						<Route>
							<xsl:value-of select="$VmarkerloopRoute"/>
						</Route>
					</xsl:for-each>
					<xsl:for-each select="PRSCode">
						<xsl:variable name="VmarkerloopPRSCode" select="."/>
						<PRSCode>
							<xsl:value-of select="$VmarkerloopPRSCode"/>
						</PRSCode>
					</xsl:for-each>
					<xsl:for-each select="PRSName">
						<xsl:variable name="VmarkerloopPRSName" select="."/>
						<PRSName>
							<xsl:value-of select="$VmarkerloopPRSName"/>
						</PRSName>
					</xsl:for-each>
					<xsl:for-each select="PRSIdentification">
						<xsl:variable name="VmarkerloopPRSIdentification" select="."/>
						<PRSIdentification>
							<xsl:value-of select="$VmarkerloopPRSIdentification"/>
						</PRSIdentification>
					</xsl:for-each>
					<xsl:for-each select="Information">
						<xsl:variable name="VmarkerloopInformation" select="."/>
						<Information>
							<xsl:value-of select="$VmarkerloopInformation"/>
						</Information>
					</xsl:for-each>
					<xsl:for-each select="InspectionProcedure">
						<xsl:variable name="VmarkerloopInspectionProcedure" select="."/>
						<InspectionProcedure>
							<xsl:value-of select="$VmarkerloopInspectionProcedure"/>
						</InspectionProcedure>
					</xsl:for-each>
					<xsl:for-each select="PRSObjects">
						<PRSObjects>
							<xsl:for-each select="ObjectName">
								<xsl:variable name="VmarkerloopObjectName" select="."/>
								<ObjectName>
									<xsl:value-of select="$VmarkerloopObjectName"/>
								</ObjectName>
							</xsl:for-each>
							<xsl:for-each select="ObjectID">
								<xsl:variable name="VmarkerloopObjectID" select="."/>
								<ObjectID>
									<xsl:value-of select="$VmarkerloopObjectID"/>
								</ObjectID>
							</xsl:for-each>
							<xsl:for-each select="MeasurePoint">
								<xsl:variable name="VmarkerloopMeasurePoint" select="."/>
								<MeasurePoint>
									<xsl:value-of select="$VmarkerloopMeasurePoint"/>
								</MeasurePoint>
							</xsl:for-each>
							<xsl:for-each select="MeasurePointID">
								<xsl:variable name="VmarkerloopMeasurePointID" select="."/>
								<MeasurePointID>
									<xsl:value-of select="$VmarkerloopMeasurePointID"/>
								</MeasurePointID>
							</xsl:for-each>
							<xsl:for-each select="FieldNo">
								<xsl:variable name="VmarkerloopFieldNo" select="."/>
								<FieldNo>
									<xsl:value-of select="$VmarkerloopFieldNo"/>
								</FieldNo>
							</xsl:for-each>
						</PRSObjects>
					</xsl:for-each>
				</PRS>
			</xsl:for-each>
			<xsl:for-each select="PRS">
				<xsl:for-each select="GasControlLine">
					<GasControlLine>
						<xsl:for-each select="PRSName">
							<xsl:variable name="VmarkerloopPRSName2" select="."/>
							<PRSName>
								<xsl:value-of select="$VmarkerloopPRSName2"/>
							</PRSName>
						</xsl:for-each>
						<xsl:for-each select="PRSIdentification">
							<xsl:variable name="VmarkerloopPRSIdentification2" select="."/>
							<PRSIdentification>
								<xsl:value-of select="$VmarkerloopPRSIdentification2"/>
							</PRSIdentification>
						</xsl:for-each>
						<xsl:for-each select="GasControlLineName">
							<xsl:variable name="VmarkerloopGasControlLineName" select="."/>
							<GasControlLineName>
								<xsl:value-of select="$VmarkerloopGasControlLineName"/>
							</GasControlLineName>
						</xsl:for-each>
						<xsl:for-each select="PeMin">
							<xsl:variable name="VmarkerloopPeMin" select="."/>
							<PeMin>
								<xsl:value-of select="$VmarkerloopPeMin"/>
							</PeMin>
						</xsl:for-each>
						<xsl:for-each select="PeMax">
							<xsl:variable name="VmarkerloopPeMax" select="."/>
							<PeMax>
								<xsl:value-of select="$VmarkerloopPeMax"/>
							</PeMax>
						</xsl:for-each>
						<xsl:for-each select="VolumeVA">
							<xsl:variable name="VmarkerloopVolumeVA" select="."/>
							<VolumeVA>
								<xsl:value-of select="$VmarkerloopVolumeVA"/>
							</VolumeVA>
						</xsl:for-each>
						<xsl:for-each select="VolumeVAK">
							<xsl:variable name="VmarkerloopVolumeVAK" select="."/>
							<VolumeVAK>
								<xsl:value-of select="$VmarkerloopVolumeVAK"/>
							</VolumeVAK>
						</xsl:for-each>
						<xsl:for-each select="PaRangeDM">
							<xsl:variable name="VmarkerloopPaRangeDM" select="."/>
							<PaRangeDM>
								<xsl:value-of select="$VmarkerloopPaRangeDM"/>
							</PaRangeDM>
						</xsl:for-each>
						<xsl:for-each select="PeRangeDM">
							<xsl:variable name="VmarkerloopPeRangeDM" select="."/>
							<PeRangeDM>
								<xsl:value-of select="$VmarkerloopPeRangeDM"/>
							</PeRangeDM>
						</xsl:for-each>
						<xsl:for-each select="GCLIdentification">
							<xsl:variable name="VmarkerloopGCLIdentification" select="."/>
							<GCLIdentification>
								<xsl:value-of select="$VmarkerloopGCLIdentification"/>
							</GCLIdentification>
						</xsl:for-each>
						<xsl:for-each select="GCLCode">
							<xsl:variable name="VmarkerloopGCLCode" select="."/>
							<GCLCode>
								<xsl:value-of select="$VmarkerloopGCLCode"/>
							</GCLCode>
						</xsl:for-each>
						<xsl:for-each select="InspectionProcedure">
							<xsl:variable name="VmarkerloopInspectionProcedure2" select="."/>
							<InspectionProcedure>
								<xsl:value-of select="$VmarkerloopInspectionProcedure2"/>
							</InspectionProcedure>
						</xsl:for-each>
						<xsl:for-each select="FSDStart">
							<xsl:variable name="VmarkerloopFSDStart" select="."/>
							<FSDStart>
								<xsl:value-of select="$VmarkerloopFSDStart"/>
							</FSDStart>
						</xsl:for-each>
						<xsl:for-each select="GCLObjects">
							<GCLObjects>
								<xsl:for-each select="ObjectName">
									<xsl:variable name="VmarkerloopObjectName2" select="."/>
									<ObjectName>
										<xsl:value-of select="$VmarkerloopObjectName2"/>
									</ObjectName>
								</xsl:for-each>
								<xsl:for-each select="ObjectID">
									<xsl:variable name="VmarkerloopObjectID2" select="."/>
									<ObjectID>
										<xsl:value-of select="$VmarkerloopObjectID2"/>
									</ObjectID>
								</xsl:for-each>
								<xsl:for-each select="MeasurePoint">
									<xsl:variable name="VmarkerloopMeasurePoint2" select="."/>
									<MeasurePoint>
										<xsl:value-of select="$VmarkerloopMeasurePoint2"/>
									</MeasurePoint>
								</xsl:for-each>
								<xsl:for-each select="MeasurePointID">
									<xsl:variable name="VmarkerloopMeasurePointID2" select="."/>
									<MeasurePointID>
										<xsl:value-of select="$VmarkerloopMeasurePointID2"/>
									</MeasurePointID>
								</xsl:for-each>
								<xsl:for-each select="FieldNo">
									<xsl:variable name="VmarkerloopFieldNo2" select="."/>
									<FieldNo>
										<xsl:value-of select="$VmarkerloopFieldNo2"/>
									</FieldNo>
								</xsl:for-each>
								<xsl:for-each select="Boundaries">
									<Boundaries>
										<xsl:for-each select="ValueMax">
											<xsl:variable name="VmarkerloopValueMax" select="."/>
											<ValueMax>
												<xsl:value-of select="$VmarkerloopValueMax"/>
											</ValueMax>
										</xsl:for-each>
										<xsl:for-each select="ValueMin">
											<xsl:variable name="VmarkerloopValueMin" select="."/>
											<ValueMin>
												<xsl:value-of select="$VmarkerloopValueMin"/>
											</ValueMin>
										</xsl:for-each>
										<xsl:for-each select="UOV">
											<xsl:variable name="VmarkerloopUOV" select="."/>
											<UOV>
												<xsl:value-of select="$VmarkerloopUOV"/>
											</UOV>
										</xsl:for-each>
									</Boundaries>
								</xsl:for-each>
							</GCLObjects>
						</xsl:for-each>
					</GasControlLine>
				</xsl:for-each>
			</xsl:for-each>
		</PRSData>
	</xsl:template>
</xsl:stylesheet>
