'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class INSPECTORPRSResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.INSPECTOR.PRS.INSPECTORPRSResx", GetType(INSPECTORPRSResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FieldNo.
        '''</summary>
        Friend Shared ReadOnly Property str_FieldNo() As String
            Get
                Return ResourceManager.GetString("str_FieldNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLCode.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLCode() As String
            Get
                Return ResourceManager.GetString("str_FldGCLCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLFSDStart.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLFSDStart() As String
            Get
                Return ResourceManager.GetString("str_FldGCLFSDStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLIdentification.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLIdentification() As String
            Get
                Return ResourceManager.GetString("str_FldGCLIdentification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLInspectionProcedure.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLInspectionProcedure() As String
            Get
                Return ResourceManager.GetString("str_FldGCLInspectionProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLName.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLName() As String
            Get
                Return ResourceManager.GetString("str_FldGCLName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLObjectect.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLObjectect() As String
            Get
                Return ResourceManager.GetString("str_FldGCLObjectect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLPaRangeDM.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLPaRangeDM() As String
            Get
                Return ResourceManager.GetString("str_FldGCLPaRangeDM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLPeMax.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLPeMax() As String
            Get
                Return ResourceManager.GetString("str_FldGCLPeMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLPeMin.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLPeMin() As String
            Get
                Return ResourceManager.GetString("str_FldGCLPeMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLPeRangeDM.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLPeRangeDM() As String
            Get
                Return ResourceManager.GetString("str_FldGCLPeRangeDM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLVolumeVA.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLVolumeVA() As String
            Get
                Return ResourceManager.GetString("str_FldGCLVolumeVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldGCLVolumeVAK.
        '''</summary>
        Friend Shared ReadOnly Property str_FldGCLVolumeVAK() As String
            Get
                Return ResourceManager.GetString("str_FldGCLVolumeVAK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldPRSCode.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSCode() As String
            Get
                Return ResourceManager.GetString("str_FldPRSCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldPRSGasControlLines.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSGasControlLines() As String
            Get
                Return ResourceManager.GetString("str_FldPRSGasControlLines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldPRSIdentification.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSIdentification() As String
            Get
                Return ResourceManager.GetString("str_FldPRSIdentification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Information.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSInformation() As String
            Get
                Return ResourceManager.GetString("str_FldPRSInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldPRSInspectionProcedure.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSInspectionProcedure() As String
            Get
                Return ResourceManager.GetString("str_FldPRSInspectionProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldPRSName.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSName() As String
            Get
                Return ResourceManager.GetString("str_FldPRSName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !fldPRSObject.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSObject() As String
            Get
                Return ResourceManager.GetString("str_FldPRSObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FldPRSRoute.
        '''</summary>
        Friend Shared ReadOnly Property str_FldPRSRoute() As String
            Get
                Return ResourceManager.GetString("str_FldPRSRoute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspection Completed.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionCompleted() As String
            Get
                Return ResourceManager.GetString("str_InspectionCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Deleted.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionDeleted() As String
            Get
                Return ResourceManager.GetString("str_InspectionDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !No Inspection procedure found.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionNoProcedure() As String
            Get
                Return ResourceManager.GetString("str_InspectionNoProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Not inspected.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionNotInspected() As String
            Get
                Return ResourceManager.GetString("str_InspectionNotInspected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspection Value out of limits.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionOutOfLimits() As String
            Get
                Return ResourceManager.GetString("str_InspectionOutOfLimits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspection started but not completed.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionStartedNotCompleted() As String
            Get
                Return ResourceManager.GetString("str_InspectionStartedNotCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !MeasurePoint.
        '''</summary>
        Friend Shared ReadOnly Property str_MeasurePoint() As String
            Get
                Return ResourceManager.GetString("str_MeasurePoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !MeasurePointID.
        '''</summary>
        Friend Shared ReadOnly Property str_MeasurePointID() As String
            Get
                Return ResourceManager.GetString("str_MeasurePointID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ObjectName.
        '''</summary>
        Friend Shared ReadOnly Property str_ObjectName() As String
            Get
                Return ResourceManager.GetString("str_ObjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ObjectNameID.
        '''</summary>
        Friend Shared ReadOnly Property str_ObjectNameID() As String
            Get
                Return ResourceManager.GetString("str_ObjectNameID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLareCompleted.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionCompleted() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLareDeleted.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionDeleted() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLNoProcedure.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionNoProcedure() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionNoProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLNotInspected.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionNotInspected() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionNotInspected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLOutOfLimits.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionOutOfLimits() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionOutOfLimits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLInspectionNotStarted.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionStartedNotCompleted() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionStartedNotCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AllGCLInspectionsWarning.
        '''</summary>
        Friend Shared ReadOnly Property str_PRSGCLInspectionWarning() As String
            Get
                Return ResourceManager.GetString("str_PRSGCLInspectionWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Status.
        '''</summary>
        Friend Shared ReadOnly Property str_Status() As String
            Get
                Return ResourceManager.GetString("str_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !UOV.
        '''</summary>
        Friend Shared ReadOnly Property str_UOV() As String
            Get
                Return ResourceManager.GetString("str_UOV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueMax.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueMax() As String
            Get
                Return ResourceManager.GetString("str_ValueMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueMin.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueMin() As String
            Get
                Return ResourceManager.GetString("str_ValueMin", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
