//////////////////////////////////////////////////////////////////////////////////
// Initially Generated by Sioux C# StateMachine Code Generator 					//
//  User changes allowed, requires merging when re-generated		            //
//////////////////////////////////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class Connected : ConnectedBase
    {
        public Connected(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public override void SendCommandTrigger(Infra.DeviceCommand command, string commandParameter)
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            base.SendCommandTrigger(command, commandParameter);

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }

        public override void DisconnectTrigger()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL
            ((ConnectionStateMachine)stateMachine).Hal.IsBusy = false;

            base.DisconnectTrigger();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }

        public override void StartContinuousMeasurementTrigger(int measurementFrequency)
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL
            ((ConnectionStateMachine)stateMachine).ContinuousMeasureReason = ContinuousMeasureReason.START;
            base.StartContinuousMeasurementTrigger(measurementFrequency);

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }


        // State Behaviors

        public override void entry()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE ENTRY CALL

            base.entry();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE ENTRY CALL	
        }

        public override void body()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE BODY (DO) CALL

            base.body();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE BODY (DO) CALL
        }

        public override void exit()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE EXIT CALL

            base.exit();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE EXIT CALL
        }
    }
}
