//////////////////////////////////////////////////////////////////////////////////
// Initially Generated by Sioux C# StateMachine Code Generator 					//
//  User changes allowed, requires merging when re-generated		            //
//////////////////////////////////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class Connecting : ConnectingBase
    {
        public Connecting(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public override void ConnectFailedTrigger(string message, int errorCode)
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            ((ConnectionStateMachine)stateMachine).DisconnectedReason = DisconnectedReason.CONNECTFAILED;

            base.ConnectFailedTrigger(message, errorCode);

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }

        public override void ConnectedTrigger()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            ((ConnectionStateMachine)stateMachine).ConnectedReason = ConnectedReason.CONNECTING;

            base.ConnectedTrigger();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }


        // State Behaviors

        public override void body()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE BODY (DO) CALL

            base.body();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE BODY (DO) CALL
        }
    }
}
