'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CommunicatorPDAresx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.COMMUNICATOR.Synchronize.Infra.CommunicatorPDAresx", GetType(CommunicatorPDAresx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  !Amount of data: .
        '''</summary>
        Friend Shared ReadOnly Property str_Amount_of_data() As String
            Get
                Return ResourceManager.GetString("str_Amount_of_data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Battery.
        '''</summary>
        Friend Shared ReadOnly Property str_Battery() As String
            Get
                Return ResourceManager.GetString("str_Battery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !BatteryLifePercent.
        '''</summary>
        Friend Shared ReadOnly Property str_BatteryLifePercent() As String
            Get
                Return ResourceManager.GetString("str_BatteryLifePercent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !BatteryLifeTime.
        '''</summary>
        Friend Shared ReadOnly Property str_BatteryLifeTime() As String
            Get
                Return ResourceManager.GetString("str_BatteryLifeTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Click button to start synchronisation INSEPCTOR PC.
        '''</summary>
        Friend Shared ReadOnly Property str_ClickButtonToStartSyncInspectorPC() As String
            Get
                Return ResourceManager.GetString("str_ClickButtonToStartSyncInspectorPC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The file &apos;COMMUNICATORData.mdb&apos; can not be found on the pc.
        '''</summary>
        Friend Shared ReadOnly Property str_CommunicatorDbNotFound() As String
            Get
                Return ResourceManager.GetString("str_CommunicatorDbNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !% Completed.
        '''</summary>
        Friend Shared ReadOnly Property str_Completed() As String
            Get
                Return ResourceManager.GetString("str_Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  connection.
        '''</summary>
        Friend Shared ReadOnly Property str_connection() As String
            Get
                Return ResourceManager.GetString("str_connection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Copy file: .
        '''</summary>
        Friend Shared ReadOnly Property str_Copy_file() As String
            Get
                Return ResourceManager.GetString("str_Copy_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The directory for the results file is not found. Do you wish to continue?.
        '''</summary>
        Friend Shared ReadOnly Property str_DataDirPCNotFound() As String
            Get
                Return ResourceManager.GetString("str_DataDirPCNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Device free storage.
        '''</summary>
        Friend Shared ReadOnly Property str_Device_free_storage() As String
            Get
                Return ResourceManager.GetString("str_Device_free_storage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Disconnection.
        '''</summary>
        Friend Shared ReadOnly Property str_Disconnection() As String
            Get
                Return ResourceManager.GetString("str_Disconnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Unable to write file.
        '''</summary>
        Friend Shared ReadOnly Property str_ErrorWriteFile() As String
            Get
                Return ResourceManager.GetString("str_ErrorWriteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The xml file is not valid (XSD error).
        '''</summary>
        Friend Shared ReadOnly Property str_ErrorXsdValidation() As String
            Get
                Return ResourceManager.GetString("str_ErrorXsdValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The file does not exists.
        '''</summary>
        Friend Shared ReadOnly Property str_FileNotExists() As String
            Get
                Return ResourceManager.GetString("str_FileNotExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !File path:.
        '''</summary>
        Friend Shared ReadOnly Property str_FilePath() As String
            Get
                Return ResourceManager.GetString("str_FilePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !hours.
        '''</summary>
        Friend Shared ReadOnly Property str_hours() As String
            Get
                Return ResourceManager.GetString("str_hours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !INSPECTOR.
        '''</summary>
        Friend Shared ReadOnly Property str_INSPECTOR() As String
            Get
                Return ResourceManager.GetString("str_INSPECTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !InspectorInfoMessage.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectorInfoMessage() As String
            Get
                Return ResourceManager.GetString("str_InspectorInfoMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !InspectorInfoStepIDText.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectorInfoStepIDText() As String
            Get
                Return ResourceManager.GetString("str_InspectorInfoStepIDText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !InspectorInfoStepMainID.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectorInfoStepMainID() As String
            Get
                Return ResourceManager.GetString("str_InspectorInfoStepMainID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !InspectorInfoStepMainIDText.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectorInfoStepMainIDText() As String
            Get
                Return ResourceManager.GetString("str_InspectorInfoStepMainIDText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !INSPECTORSerialNumber.
        '''</summary>
        Friend Shared ReadOnly Property str_INSPECTORSerialNumber() As String
            Get
                Return ResourceManager.GetString("str_INSPECTORSerialNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !INSPECTORSubVersion.
        '''</summary>
        Friend Shared ReadOnly Property str_INSPECTORSubVersion() As String
            Get
                Return ResourceManager.GetString("str_INSPECTORSubVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !INSPECTORVersion.
        '''</summary>
        Friend Shared ReadOnly Property str_INSPECTORVersion() As String
            Get
                Return ResourceManager.GetString("str_INSPECTORVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Main directory Archive.
        '''</summary>
        Friend Shared ReadOnly Property str_MainDirArchive() As String
            Get
                Return ResourceManager.GetString("str_MainDirArchive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Main directory Inspection procedure.
        '''</summary>
        Friend Shared ReadOnly Property str_MainDirInspectionProcedure() As String
            Get
                Return ResourceManager.GetString("str_MainDirInspectionProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Main directory Measurementdata.
        '''</summary>
        Friend Shared ReadOnly Property str_MainDirMeasurementData() As String
            Get
                Return ResourceManager.GetString("str_MainDirMeasurementData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Main directory PLEXOR.
        '''</summary>
        Friend Shared ReadOnly Property str_MainDirPlexor() As String
            Get
                Return ResourceManager.GetString("str_MainDirPlexor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Main directory PRS.
        '''</summary>
        Friend Shared ReadOnly Property str_MainDirPRS() As String
            Get
                Return ResourceManager.GetString("str_MainDirPRS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Main directory Result.
        '''</summary>
        Friend Shared ReadOnly Property str_MainDirResult() As String
            Get
                Return ResourceManager.GetString("str_MainDirResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !minutes.
        '''</summary>
        Friend Shared ReadOnly Property str_minutes() As String
            Get
                Return ResourceManager.GetString("str_minutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Processor.
        '''</summary>
        Friend Shared ReadOnly Property str_Processor() As String
            Get
                Return ResourceManager.GetString("str_Processor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ProcessorType.
        '''</summary>
        Friend Shared ReadOnly Property str_ProcessorType() As String
            Get
                Return ResourceManager.GetString("str_ProcessorType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SavingFile.
        '''</summary>
        Friend Shared ReadOnly Property str_SavingFile() As String
            Get
                Return ResourceManager.GetString("str_SavingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Storage.
        '''</summary>
        Friend Shared ReadOnly Property str_Storage() As String
            Get
                Return ResourceManager.GetString("str_Storage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Synchronization is completed.
        '''</summary>
        Friend Shared ReadOnly Property str_Synchronization_is_completed() As String
            Get
                Return ResourceManager.GetString("str_Synchronization_is_completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !It is not possible to start synchronisation; No inspector PC installed.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncNotStartedNoInspectorPC() As String
            Get
                Return ResourceManager.GetString("str_SyncNotStartedNoInspectorPC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !It is not possible to start synchronisation; PDA connected.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncNotStartedPdaConnect() As String
            Get
                Return ResourceManager.GetString("str_SyncNotStartedPdaConnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SyncStatusDateTime.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncStatusDateTime() As String
            Get
                Return ResourceManager.GetString("str_SyncStatusDateTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SyncStatusStatusIcon.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncStatusStatusIcon() As String
            Get
                Return ResourceManager.GetString("str_SyncStatusStatusIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SyncStatusStatusText.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncStatusStatusText() As String
            Get
                Return ResourceManager.GetString("str_SyncStatusStatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SyncStatusStepID.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncStatusStepID() As String
            Get
                Return ResourceManager.GetString("str_SyncStatusStepID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SyncStatusStepMessage.
        '''</summary>
        Friend Shared ReadOnly Property str_SyncStatusStepMessage() As String
            Get
                Return ResourceManager.GetString("str_SyncStatusStepMessage", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
