'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SyncStepStatusResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.COMMUNICATOR.Synchronize.Infra.SyncStepStatusResx", GetType(SyncStepStatusResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Get_Path_Pda.
        '''</summary>
        Friend Shared ReadOnly Property Step_5000() As String
            Get
                Return ResourceManager.GetString("Step_5000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Get_Inspector_Information.
        '''</summary>
        Friend Shared ReadOnly Property Step_5001() As String
            Get
                Return ResourceManager.GetString("Step_5001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Update_Software_in_Database.
        '''</summary>
        Friend Shared ReadOnly Property Step_5002() As String
            Get
                Return ResourceManager.GetString("Step_5002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Getting_Paths_From_Database.
        '''</summary>
        Friend Shared ReadOnly Property Step_5003() As String
            Get
                Return ResourceManager.GetString("Step_5003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Creating_temp_directory.
        '''</summary>
        Friend Shared ReadOnly Property Step_5004() As String
            Get
                Return ResourceManager.GetString("Step_5004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Getting_pda_information.
        '''</summary>
        Friend Shared ReadOnly Property Step_5005() As String
            Get
                Return ResourceManager.GetString("Step_5005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Copy_files_From_Inspector.
        '''</summary>
        Friend Shared ReadOnly Property Step_5006() As String
            Get
                Return ResourceManager.GetString("Step_5006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Process_Result_file_Inspector.
        '''</summary>
        Friend Shared ReadOnly Property Step_5007() As String
            Get
                Return ResourceManager.GetString("Step_5007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Delete_Result_files_Inspector.
        '''</summary>
        Friend Shared ReadOnly Property Step_5008() As String
            Get
                Return ResourceManager.GetString("Step_5008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Create_Station_information_File.
        '''</summary>
        Friend Shared ReadOnly Property Step_5009() As String
            Get
                Return ResourceManager.GetString("Step_5009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Delete_station_File_Inspector.
        '''</summary>
        Friend Shared ReadOnly Property Step_5010() As String
            Get
                Return ResourceManager.GetString("Step_5010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Copy_files_to_Inspector.
        '''</summary>
        Friend Shared ReadOnly Property Step_5011() As String
            Get
                Return ResourceManager.GetString("Step_5011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Transfer_Completed.
        '''</summary>
        Friend Shared ReadOnly Property Step_5012() As String
            Get
                Return ResourceManager.GetString("Step_5012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Create_Results_file.
        '''</summary>
        Friend Shared ReadOnly Property Step_5013() As String
            Get
                Return ResourceManager.GetString("Step_5013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Delete_Temp_and_SystemIntegration_files.
        '''</summary>
        Friend Shared ReadOnly Property Step_5014() As String
            Get
                Return ResourceManager.GetString("Step_5014", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
