///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////
using System;

namespace Inspector.Connection
{
    public class ConnectFailedEventArgs : EventArgs
    {
        public ConnectFailedEventArgs(string message, int errorCode)
        {
            this.Message = message;
            this.ErrorCode = errorCode;
        }

        public string Message { get; set; }
        public int ErrorCode { get; set; }
    }
}
