///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////
using System;

namespace Inspector.Connection
{
    public class MessageReceivedEventArgs : EventArgs
    {
        public MessageReceivedEventArgs(string data)
        {
            this.Data = data;
        }

        public string Data { get; set; }
    }
}
