//////////////////////////////////////////////////////////////////////////////////
// Initially Generated by Sioux C# StateMachine Code Generator 					//
//  User changes allowed, requires merging when re-generated		            //
//////////////////////////////////////////////////////////////////////////////////

using System.Collections.Generic;
using Inspector.Model.BluetoothDongle;
using StateMachines.Base;

namespace Inspector.Connection
{
    public class Disconnected : DisconnectedBase
    {
        public Disconnected(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public override void DisconnectTrigger()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL
            ((ConnectionStateMachine)stateMachine).DisconnectedReason = DisconnectedReason.DISCONNECTED;

            base.DisconnectTrigger();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }

        public override void ConnectTrigger(Dictionary<string, string> connectionParameters, List<BluetoothDongleInformation> allowedBluetoothDongles)
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            base.ConnectTrigger(connectionParameters, allowedBluetoothDongles);

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }

        public override void UnPairDevicesTrigger(string address)
        {

            base.UnPairDevicesTrigger(address);

        }

        public override void DeviceUnPairedTrigger(string address)
        {
            base.DeviceUnPairedTrigger(address);
        }

        public override void DeviceUnPairFinishedTrigger()
        {
            base.DeviceUnPairFinishedTrigger();
        }
        // State Behaviors

        public override void body()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE BODY (DO) CALL

            base.body();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE BODY (DO) CALL
        }
    }
}
