//////////////////////////////////////////////////////////////////////////////////
// Initially Generated by Sioux C# StateMachine Code Generator 					//
//  User changes allowed, requires merging when re-generated		            //
//////////////////////////////////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class Disconnecting : DisconnectingBase
    {
        public Disconnecting(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public override void DisconnectedTrigger()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            ((ConnectionStateMachine)stateMachine).DisconnectedReason = DisconnectedReason.DISCONNECTING;

            base.DisconnectedTrigger();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }


        // State Behaviors

        public override void body()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE BODY (DO) CALL

            base.body();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE BODY (DO) CALL
        }
    }
}
