'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TelerikGridResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.COMMUNICATOR.Main.TelerikGridResx", GetType(TelerikGridResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ColumnChooserFormCaption.
        '''</summary>
        Friend Shared ReadOnly Property ColumnChooserFormCaption() As String
            Get
                Return ResourceManager.GetString("ColumnChooserFormCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !AddNewRowString.
        '''</summary>
        Friend Shared ReadOnly Property str_AddNewRowString() As String
            Get
                Return ResourceManager.GetString("str_AddNewRowString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !BestFitMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_BestFitMenuItem() As String
            Get
                Return ResourceManager.GetString("str_BestFitMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ClearSortingMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_ClearSortingMenuItem() As String
            Get
                Return ResourceManager.GetString("str_ClearSortingMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ColumnChooserFormMessage.
        '''</summary>
        Friend Shared ReadOnly Property str_ColumnChooserFormMessage() As String
            Get
                Return ResourceManager.GetString("str_ColumnChooserFormMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ColumnChooserMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_ColumnChooserMenuItem() As String
            Get
                Return ResourceManager.GetString("str_ColumnChooserMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingChkApplyToRow.
        '''</summary>
        Friend Shared ReadOnly Property str_Conditional_ApplyToRow() As String
            Get
                Return ResourceManager.GetString("str_Conditional_ApplyToRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingBtnAdd.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingBtnAdd() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingBtnAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingBtnApply.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingBtnApply() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingBtnApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingBtnCancel.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingBtnCancel() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingBtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingBtnOK.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingBtnOK() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingBtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingBtnRemove.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingBtnRemove() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingBtnRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingCaption.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingCaption() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingLblColumn.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingLblColumn() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingLblColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingLblName.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingLblName() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingLblName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingLblType.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingLblType() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingLblType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingLblValue1.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingLblValue() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingLblValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingLblValue2.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingLblValue1() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingLblValue1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalFormattingMenuItem() As String
            Get
                Return ResourceManager.GetString("str_ConditionalFormattingMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingGrpConditions.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalGrpConditions() As String
            Get
                Return ResourceManager.GetString("str_ConditionalGrpConditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingGrpProperties.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalGrpProperties() As String
            Get
                Return ResourceManager.GetString("str_ConditionalGrpProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ConditionalFormattingRuleAppliesOn.
        '''</summary>
        Friend Shared ReadOnly Property str_ConditionalRuleAppliesOn() As String
            Get
                Return ResourceManager.GetString("str_ConditionalRuleAppliesOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CopyMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_CopyMenuItem() As String
            Get
                Return ResourceManager.GetString("str_CopyMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogBtnCancel.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogBtnCancel() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogBtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogBtnOk.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogBtnOk() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogBtnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogCaption.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogCaption() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogCheckBoxNot.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogCheckBoxNot() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogCheckBoxNot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogLabel.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogLabel() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogRbAnd.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogRbAnd() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogRbAnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterDialogRbOr.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterDialogRbOr() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterDialogRbOr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !CustomFilterMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_CustomFilterMenuItem() As String
            Get
                Return ResourceManager.GetString("str_CustomFilterMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !DeleteRowMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_DeleteRowMenuItem() As String
            Get
                Return ResourceManager.GetString("str_DeleteRowMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !EditMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_EditMenuItem() As String
            Get
                Return ResourceManager.GetString("str_EditMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionBetween.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionBetween() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionBetween", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionContains.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionContains() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionContains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionCustom.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionCustom() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionDoesNotContain.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionDoesNotContain() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionDoesNotContain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionEndsWith.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionEndsWith() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionEndsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionEqualTo() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionGreaterThan.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionGreaterThan() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionGreaterThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionGreaterThanOrEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionGreatorEqual() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionGreatorEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionIsEmpty.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionIsEmpty() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionIsNull.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionIsNull() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionLessThan.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionLessThan() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionLessThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionLessThanOrEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionLessThanOrEqualTo() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionLessThanOrEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionNoFilter.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionNoFilter() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionNoFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionNotBetween.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionNotBetween() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionNotBetween", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionNotEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionNotEqualTo() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionNotEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionNotIsEmpty.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionNotIsEmpty() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionNotIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionNotIsNull.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionNotIsNull() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionNotIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterFunctionStartsWith.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterFunctionStartsWith() As String
            Get
                Return ResourceManager.GetString("str_FilterFunctionStartsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorBetween.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorBetween() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorBetween", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorContains.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorContains() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorContains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorCustom.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorCustom() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorDoesNotContain.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorDoesNotContain() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorDoesNotContain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorEndsWith.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorEndsWith() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorEndsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorEqualTo() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorGreaterThan.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorGreaterThan() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorGreaterThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorGreaterThanOrEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorGreatorEqual() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorGreatorEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorIsContainedIn.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorIsContainedIn() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorIsContainedIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorIsEmpty.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorIsEmpty() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorIsLike.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorIsLike() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorIsLike", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorIsNull.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorIsNull() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorLessThan.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorLessThan() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorLessThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorLessThanOrEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorLessThanOrEqualTo() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorLessThanOrEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNoFilter.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNoFilter() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNoFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNotBetween.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNotBetween() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNotBetween", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNotEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNotEqualTo() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNotEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNotIsContainedIn.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNotIsContainedIn() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNotIsContainedIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNotIsEmpty.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNotIsEmpty() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNotIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNotIsLike.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNotIsLike() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNotIsLike", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorNotIsNull.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorNotIsNull() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorNotIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !FilterOperatorStartsWith.
        '''</summary>
        Friend Shared ReadOnly Property str_FilterOperatorStartsWith() As String
            Get
                Return ResourceManager.GetString("str_FilterOperatorStartsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !GroupByThisColumnMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_GroupByThisColumnMenuItem() As String
            Get
                Return ResourceManager.GetString("str_GroupByThisColumnMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !HideMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_HideMenuItem() As String
            Get
                Return ResourceManager.GetString("str_HideMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !PasteMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_PasteMenuItem() As String
            Get
                Return ResourceManager.GetString("str_PasteMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !PinAtLeftMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_PinAtLeftMenuItem() As String
            Get
                Return ResourceManager.GetString("str_PinAtLeftMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !PinAtRightMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_PinAtRightMenuItem() As String
            Get
                Return ResourceManager.GetString("str_PinAtRightMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !PinMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_PinMenuItem() As String
            Get
                Return ResourceManager.GetString("str_PinMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SortAscendingMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_SortAscendingMenuItem() As String
            Get
                Return ResourceManager.GetString("str_SortAscendingMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SortDescendingMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_SortDescendingMenuItem() As String
            Get
                Return ResourceManager.GetString("str_SortDescendingMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !StatusImage.
        '''</summary>
        Friend Shared ReadOnly Property str_StatusImage() As String
            Get
                Return ResourceManager.GetString("str_StatusImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !UngroupThisColumn.
        '''</summary>
        Friend Shared ReadOnly Property str_UngroupThisColumn() As String
            Get
                Return ResourceManager.GetString("str_UngroupThisColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !UnpinMenuItem.
        '''</summary>
        Friend Shared ReadOnly Property str_UnpinMenuItem() As String
            Get
                Return ResourceManager.GetString("str_UnpinMenuItem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
