///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////
using System;
using Inspector.Infra;

namespace Inspector.Connection
{
    public class ConnectedEventArgs : EventArgs
    {
        public ConnectedEventArgs(DeviceType deviceType)
        {
            DeviceType = deviceType;
        }

        public DeviceType DeviceType { get; set; }
    }
}
