///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using Inspector.Model;

namespace Inspector.Connection
{
    public class MeasurementEventArgs : EventArgs
    {
        public MeasurementEventArgs(IList<Measurement> measurements)
        {
            this.Measurements = measurements;
        }

        public IList<Measurement> Measurements { get; set; }
    }
}
