//////////////////////////////////////////////////////////////////////////////////
// Initially Generated by Sioux C# StateMachine Code Generator 					//
//  User changes allowed, requires merging when re-generated		            //
//////////////////////////////////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class SendingCommand : SendingCommandBase
    {
        public SendingCommand(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public override void MessageReceivedTrigger(string data)
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            ((ConnectionStateMachine)stateMachine).ConnectedReason = ConnectedReason.SENDMESSAGE;

            base.MessageReceivedTrigger(data);

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }

        public override void ErrorTrigger(string message, int errorCode)
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE TRIGGER CALL

            base.ErrorTrigger(message, errorCode);

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE TRIGGER CALL		
        }


        // State Behaviors

        public override void body()
        {
            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR BEFORE THE BODY (DO) CALL

            base.body();

            // PUT YOUR OWN CODE HERE IF THE ACTION SHOULD OCCUR AFTER THE BODY (DO) CALL
        }
    }
}
