///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////

namespace Inspector.Connection.EventTranslation
{
    /// <summary>
    /// Convert incoming events to function calls on the state machine  
    /// </summary>
    public partial class EventToCallConnectionStateMachine
    {
        private IConnectionStateMachineContext m_ConnectionStateMachineContext;

        public EventToCallConnectionStateMachine()
        {
            m_ConnectionStateMachineContext = null;
        }

        public EventToCallConnectionStateMachine(IConnectionStateMachineContext ConnectionStateMachineContext)
        {
            m_ConnectionStateMachineContext = ConnectionStateMachineContext;
        }
    }
}
