'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class INSPECTORMainResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.INSPECTOR.Main.INSPECTORMainResx", GetType(INSPECTORMainResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !An evaluation version is created..
        '''</summary>
        Friend Shared ReadOnly Property str_An_evaluation_version_is() As String
            Get
                Return ResourceManager.GetString("str_An_evaluation_version_is", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup Business logic component:.
        '''</summary>
        Friend Shared ReadOnly Property str_BusinessLogic_component() As String
            Get
                Return ResourceManager.GetString("str_BusinessLogic_component", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !China.
        '''</summary>
        Friend Shared ReadOnly Property str_China() As String
            Get
                Return ResourceManager.GetString("str_China", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Demo version. Amount of days left:.
        '''</summary>
        Friend Shared ReadOnly Property str_demo_version_days_left() As String
            Get
                Return ResourceManager.GetString("str_demo_version_days_left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Deutsch.
        '''</summary>
        Friend Shared ReadOnly Property str_Deutsch() As String
            Get
                Return ResourceManager.GetString("str_Deutsch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !English.
        '''</summary>
        Friend Shared ReadOnly Property str_English() As String
            Get
                Return ResourceManager.GetString("str_English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !File merge error, application cannot continue:.
        '''</summary>
        Friend Shared ReadOnly Property str_FileMergeError() As String
            Get
                Return ResourceManager.GetString("str_FileMergeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The file.
        '''</summary>
        Friend Shared ReadOnly Property str_FileNotExists1() As String
            Get
                Return ResourceManager.GetString("str_FileNotExists1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !does not exists.
        '''</summary>
        Friend Shared ReadOnly Property str_fileNotExists2() As String
            Get
                Return ResourceManager.GetString("str_fileNotExists2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Black.
        '''</summary>
        Friend Shared ReadOnly Property str_GraphBackColorBlack() As String
            Get
                Return ResourceManager.GetString("str_GraphBackColorBlack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !White.
        '''</summary>
        Friend Shared ReadOnly Property str_GraphBackColorWhite() As String
            Get
                Return ResourceManager.GetString("str_GraphBackColorWhite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSPECTOR PC.
        '''</summary>
        Friend Shared ReadOnly Property str_INSPECTOR_PC() As String
            Get
                Return ResourceManager.GetString("str_INSPECTOR_PC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup Infra component: .
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_Infra_component() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_Infra_component", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup inspectieprocedure component: .
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_inspectieprocedure() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_inspectieprocedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup PLEXOR component: .
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_PLEXOR_component() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_PLEXOR_component", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Kamstrup PRS component: .
        '''</summary>
        Friend Shared ReadOnly Property str_Kamstrup_PRS_component() As String
            Get
                Return ResourceManager.GetString("str_Kamstrup_PRS_component", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Center.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Alignment_Center() As String
            Get
                Return ResourceManager.GetString("str_legend_Alignment_Center", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Far.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Alignment_Far() As String
            Get
                Return ResourceManager.GetString("str_legend_Alignment_Far", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Near.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Alignment_Near() As String
            Get
                Return ResourceManager.GetString("str_legend_Alignment_Near", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !False.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_DockinChart_False() As String
            Get
                Return ResourceManager.GetString("str_legend_DockinChart_False", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !True.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_DockinChart_True() As String
            Get
                Return ResourceManager.GetString("str_legend_DockinChart_True", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Bottom.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Docking_Bottom() As String
            Get
                Return ResourceManager.GetString("str_legend_Docking_Bottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Left.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Docking_Left() As String
            Get
                Return ResourceManager.GetString("str_legend_Docking_Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Right.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Docking_Right() As String
            Get
                Return ResourceManager.GetString("str_legend_Docking_Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Top.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Docking_Top() As String
            Get
                Return ResourceManager.GetString("str_legend_Docking_Top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Column.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Style_Column() As String
            Get
                Return ResourceManager.GetString("str_legend_Style_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Row.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Style_Row() As String
            Get
                Return ResourceManager.GetString("str_legend_Style_Row", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Table.
        '''</summary>
        Friend Shared ReadOnly Property str_legend_Style_Table() As String
            Get
                Return ResourceManager.GetString("str_legend_Style_Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The license is Expired.
        '''</summary>
        Friend Shared ReadOnly Property str_license_expired() As String
            Get
                Return ResourceManager.GetString("str_license_expired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !License to:.
        '''</summary>
        Friend Shared ReadOnly Property str_License_to() As String
            Get
                Return ResourceManager.GetString("str_License_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Nederlands.
        '''</summary>
        Friend Shared ReadOnly Property str_Nederlands() As String
            Get
                Return ResourceManager.GetString("str_Nederlands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The user has no administrator rights to save license information!.
        '''</summary>
        Friend Shared ReadOnly Property str_NoAdministratorAccessToRegister() As String
            Get
                Return ResourceManager.GetString("str_NoAdministratorAccessToRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Please sent the mail to registration@ww-gas.com.
        '''</summary>
        Friend Shared ReadOnly Property str_Please_sent_the_mail_to() As String
            Get
                Return ResourceManager.GetString("str_Please_sent_the_mail_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Poliski.
        '''</summary>
        Friend Shared ReadOnly Property str_Poland() As String
            Get
                Return ResourceManager.GetString("str_Poland", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Changes are applied after restarting the program. Do you wish to restart the program?.
        '''</summary>
        Friend Shared ReadOnly Property str_Restart_application() As String
            Get
                Return ResourceManager.GetString("str_Restart_application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Russisch.
        '''</summary>
        Friend Shared ReadOnly Property str_Russia() As String
            Get
                Return ResourceManager.GetString("str_Russia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The selected translation does not exists!.
        '''</summary>
        Friend Shared ReadOnly Property str_TranslationNotExists() As String
            Get
                Return ResourceManager.GetString("str_TranslationNotExists", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
