///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////


using StateMachines.Base;

namespace Inspector.Connection
{
    public class SendingCommandBase : State
    {
        public SendingCommandBase(StateMachine stateMachine, State superState) : base(stateMachine, superState) { }

        // Signals
        public virtual void MessageReceivedTrigger(string data)
        {
            ((ConnectionStateMachine)stateMachine).Data = data;

            SetState(typeof(Connected));
        }

        public virtual void ErrorTrigger(string message, int errorCode)
        {
            ((ConnectionStateMachine)stateMachine).Message = message;
            ((ConnectionStateMachine)stateMachine).ErrorCode = errorCode;

            SetState(typeof(Error));
        }


        // State Behaviors

        public override void body()
        {
            ((ConnectionStateMachine)stateMachine).Do_SendCommand();
        }
    }
}
