'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class InspectionProcedureResx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KAM.INSPECTOR.IP.InspectionProcedureResx", GetType(InspectionProcedureResx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Communication error.
        '''</summary>
        Friend Shared ReadOnly Property str_Communication_error() As String
            Get
                Return ResourceManager.GetString("str_Communication_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Completed.
        '''</summary>
        Friend Shared ReadOnly Property str_Completed() As String
            Get
                Return ResourceManager.GetString("str_Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !-.
        '''</summary>
        Friend Shared ReadOnly Property str_DefaultNoValue() As String
            Get
                Return ResourceManager.GetString("str_DefaultNoValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Do you wich to restart the initialization?.
        '''</summary>
        Friend Shared ReadOnly Property str_Do_you_wich_to_restart_the() As String
            Get
                Return ResourceManager.GetString("str_Do_you_wich_to_restart_the", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Do you wish to stop the inspection?.
        '''</summary>
        Friend Shared ReadOnly Property str_DoYouWishStopInspectionByUser() As String
            Get
                Return ResourceManager.GetString("str_DoYouWishStopInspectionByUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Errorcode.
        '''</summary>
        Friend Shared ReadOnly Property str_Errorcode() As String
            Get
                Return ResourceManager.GetString("str_Errorcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Extra measurement Period.
        '''</summary>
        Friend Shared ReadOnly Property str_Extra_measurement_Period() As String
            Get
                Return ResourceManager.GetString("str_Extra_measurement_Period", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Do you wish to continue without sensor [Ignore],  or retry Sensor initialisation [Retry]?.
        '''</summary>
        Friend Shared ReadOnly Property str_InitializationUiRequest() As String
            Get
                Return ResourceManager.GetString("str_InitializationUiRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspection procedure name does not exists.
        '''</summary>
        Friend Shared ReadOnly Property str_Inspection_procedure_name_does() As String
            Get
                Return ResourceManager.GetString("str_Inspection_procedure_name_does", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection is finished.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionFinished() As String
            Get
                Return ResourceManager.GetString("str_InspectionFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Inspection finished by user.
        '''</summary>
        Friend Shared ReadOnly Property str_InspectionFinishedByUser() As String
            Get
                Return ResourceManager.GetString("str_InspectionFinishedByUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !It is not allowed to run multiple inspections at the same time.
        '''</summary>
        Friend Shared ReadOnly Property str_It_is_not_allowed_to_run() As String
            Get
                Return ResourceManager.GetString("str_It_is_not_allowed_to_run", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !--------.
        '''</summary>
        Friend Shared ReadOnly Property str_LinePRStoGCL() As String
            Get
                Return ResourceManager.GetString("str_LinePRStoGCL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !List.
        '''</summary>
        Friend Shared ReadOnly Property str_List() As String
            Get
                Return ResourceManager.GetString("str_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !No option.
        '''</summary>
        Friend Shared ReadOnly Property str_No_option() As String
            Get
                Return ResourceManager.GetString("str_No_option", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Can not start inspection because no sections selected.
        '''</summary>
        Friend Shared ReadOnly Property str_NoSectionSelected() As String
            Get
                Return ResourceManager.GetString("str_NoSectionSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The measurements is outside the rejection boundaries.
        '''</summary>
        Friend Shared ReadOnly Property str_OutSideBoundaries() As String
            Get
                Return ResourceManager.GetString("str_OutSideBoundaries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !The inspection was outside boundaries. Do you wish to restart?.
        '''</summary>
        Friend Shared ReadOnly Property str_RestartBoundariesInspection() As String
            Get
                Return ResourceManager.GetString("str_RestartBoundariesInspection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SSV tripped.
        '''</summary>
        Friend Shared ReadOnly Property str_SAV_Setting() As String
            Get
                Return ResourceManager.GetString("str_SAV_Setting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SSV trip pressure.
        '''</summary>
        Friend Shared ReadOnly Property str_SAV_trapValue() As String
            Get
                Return ResourceManager.GetString("str_SAV_trapValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !~.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41_separator() As String
            Get
                Return ResourceManager.GetString("str_SC41_separator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Check No.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41List_column_CheckListNo() As String
            Get
                Return ResourceManager.GetString("str_SC41List_column_CheckListNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Check Yes.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41List_column_CheckListYes() As String
            Get
                Return ResourceManager.GetString("str_SC41List_column_CheckListYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Condition Code.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41List_column_ConditionCode() As String
            Get
                Return ResourceManager.GetString("str_SC41List_column_ConditionCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Condition Code description.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41List_column_ConditionCodeDescription() As String
            Get
                Return ResourceManager.GetString("str_SC41List_column_ConditionCodeDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Next list is not displayed.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41List_column_DoNotDisplayNextList() As String
            Get
                Return ResourceManager.GetString("str_SC41List_column_DoNotDisplayNextList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !OptionList.
        '''</summary>
        Friend Shared ReadOnly Property str_SC41List_column_OptionList() As String
            Get
                Return ResourceManager.GetString("str_SC41List_column_OptionList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !seconds remaining.
        '''</summary>
        Friend Shared ReadOnly Property str_seconds_remaining() As String
            Get
                Return ResourceManager.GetString("str_seconds_remaining", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Section.
        '''</summary>
        Friend Shared ReadOnly Property str_Section() As String
            Get
                Return ResourceManager.GetString("str_Section", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Select.
        '''</summary>
        Friend Shared ReadOnly Property str_Select() As String
            Get
                Return ResourceManager.GetString("str_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Sequence.
        '''</summary>
        Friend Shared ReadOnly Property str_Sequence() As String
            Get
                Return ResourceManager.GetString("str_Sequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Step .
        '''</summary>
        Friend Shared ReadOnly Property str_Step() As String
            Get
                Return ResourceManager.GetString("str_Step", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !SubSection.
        '''</summary>
        Friend Shared ReadOnly Property str_SubSection() As String
            Get
                Return ResourceManager.GetString("str_SubSection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !bar.
        '''</summary>
        Friend Shared ReadOnly Property str_Unit_bar() As String
            Get
                Return ResourceManager.GetString("str_Unit_bar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !dm3/h.
        '''</summary>
        Friend Shared ReadOnly Property str_Unit_dm3h() As String
            Get
                Return ResourceManager.GetString("str_Unit_dm3h", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !mbar.
        '''</summary>
        Friend Shared ReadOnly Property str_Unit_mbar() As String
            Get
                Return ResourceManager.GetString("str_Unit_mbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !mbar/min.
        '''</summary>
        Friend Shared ReadOnly Property str_Unit_mbar_min() As String
            Get
                Return ResourceManager.GetString("str_Unit_mbar_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Actual.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueActual() As String
            Get
                Return ResourceManager.GetString("str_ValueActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueAverage.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueAverage() As String
            Get
                Return ResourceManager.GetString("str_ValueAverage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValuebndMax.
        '''</summary>
        Friend Shared ReadOnly Property str_ValuebndMax() As String
            Get
                Return ResourceManager.GetString("str_ValuebndMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValuebndMin.
        '''</summary>
        Friend Shared ReadOnly Property str_ValuebndMin() As String
            Get
                Return ResourceManager.GetString("str_ValuebndMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueCurrent.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueCurrent() As String
            Get
                Return ResourceManager.GetString("str_ValueCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueLeakage.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueLeakage() As String
            Get
                Return ResourceManager.GetString("str_ValueLeakage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueMaximum.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueMaximum() As String
            Get
                Return ResourceManager.GetString("str_ValueMaximum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !ValueMimimum.
        '''</summary>
        Friend Shared ReadOnly Property str_ValueMimimum() As String
            Get
                Return ResourceManager.GetString("str_ValueMimimum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Previous value.
        '''</summary>
        Friend Shared ReadOnly Property str_ValuePrevious() As String
            Get
                Return ResourceManager.GetString("str_ValuePrevious", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Starting measurement.
        '''</summary>
        Friend Shared ReadOnly Property str_WaitingForMeasurementToStart() As String
            Get
                Return ResourceManager.GetString("str_WaitingForMeasurementToStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !Time.
        '''</summary>
        Friend Shared ReadOnly Property str_yAxisText() As String
            Get
                Return ResourceManager.GetString("str_yAxisText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
