///////////////////////////////////////////////////////
// Generated by Sioux C# StateMachine Code Generator //
//                 DO NOT EDIT				         //
///////////////////////////////////////////////////////
using System;

namespace Inspector.Connection
{
    public class RecoveredFromErrorEventArgs : EventArgs
    {
        public RecoveredFromErrorEventArgs()
        {
        }

    }
}
